/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResellerRouteImport } from './routes/reseller'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ResellerIndexRouteImport } from './routes/reseller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ResellerUsersRouteImport } from './routes/reseller.users'
import { Route as ResellerLogsRouteImport } from './routes/reseller.logs'
import { Route as ResellerLicensesRouteImport } from './routes/reseller.licenses'
import { Route as ResellerBypassRouteImport } from './routes/reseller.bypass'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStorePagesRouteImport } from './routes/admin.store-pages'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminBypassRouteImport } from './routes/admin.bypass'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PublicStatusRouteImport } from './routes/_public.status'
import { Route as PublicReviewsRouteImport } from './routes/_public.reviews'
import { Route as PublicMarketplaceRouteImport } from './routes/_public.marketplace'

const ResellerRoute = ResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerIndexRoute = ResellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ResellerUsersRoute = ResellerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ResellerRoute,
} as any)
const ResellerLogsRoute = ResellerLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ResellerRoute,
} as any)
const ResellerLicensesRoute = ResellerLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => ResellerRoute,
} as any)
const ResellerBypassRoute = ResellerBypassRouteImport.update({
  id: '/bypass',
  path: '/bypass',
  getParentRoute: () => ResellerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorePagesRoute = AdminStorePagesRouteImport.update({
  id: '/store-pages',
  path: '/store-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBypassRoute = AdminBypassRouteImport.update({
  id: '/bypass',
  path: '/bypass',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReviewsRoute = PublicReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketplaceRoute = PublicMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reseller': typeof ResellerRouteWithChildren
  '/marketplace': typeof PublicMarketplaceRoute
  '/reviews': typeof PublicReviewsRoute
  '/status': typeof PublicStatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bypass': typeof AdminBypassRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store-pages': typeof AdminStorePagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/reseller/bypass': typeof ResellerBypassRoute
  '/reseller/licenses': typeof ResellerLicensesRoute
  '/reseller/logs': typeof ResellerLogsRoute
  '/reseller/users': typeof ResellerUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/reseller/': typeof ResellerIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof PublicMarketplaceRoute
  '/reviews': typeof PublicReviewsRoute
  '/status': typeof PublicStatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bypass': typeof AdminBypassRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store-pages': typeof AdminStorePagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/reseller/bypass': typeof ResellerBypassRoute
  '/reseller/licenses': typeof ResellerLicensesRoute
  '/reseller/logs': typeof ResellerLogsRoute
  '/reseller/users': typeof ResellerUsersRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/reseller': typeof ResellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reseller': typeof ResellerRouteWithChildren
  '/_public/marketplace': typeof PublicMarketplaceRoute
  '/_public/reviews': typeof PublicReviewsRoute
  '/_public/status': typeof PublicStatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bypass': typeof AdminBypassRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store-pages': typeof AdminStorePagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/reseller/bypass': typeof ResellerBypassRoute
  '/reseller/licenses': typeof ResellerLicensesRoute
  '/reseller/logs': typeof ResellerLogsRoute
  '/reseller/users': typeof ResellerUsersRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/reseller/': typeof ResellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/reseller'
    | '/marketplace'
    | '/reviews'
    | '/status'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/bypass'
    | '/admin/files'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/store-pages'
    | '/admin/users'
    | '/reseller/bypass'
    | '/reseller/licenses'
    | '/reseller/logs'
    | '/reseller/users'
    | '/admin/'
    | '/reseller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/reviews'
    | '/status'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/bypass'
    | '/admin/files'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/store-pages'
    | '/admin/users'
    | '/reseller/bypass'
    | '/reseller/licenses'
    | '/reseller/logs'
    | '/reseller/users'
    | '/'
    | '/admin'
    | '/reseller'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/reseller'
    | '/_public/marketplace'
    | '/_public/reviews'
    | '/_public/status'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/bypass'
    | '/admin/files'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/store-pages'
    | '/admin/users'
    | '/reseller/bypass'
    | '/reseller/licenses'
    | '/reseller/logs'
    | '/reseller/users'
    | '/_public/'
    | '/admin/'
    | '/reseller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResellerRoute: typeof ResellerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reseller': {
      id: '/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof ResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/': {
      id: '/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof ResellerIndexRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/reseller/users': {
      id: '/reseller/users'
      path: '/users'
      fullPath: '/reseller/users'
      preLoaderRoute: typeof ResellerUsersRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/reseller/logs': {
      id: '/reseller/logs'
      path: '/logs'
      fullPath: '/reseller/logs'
      preLoaderRoute: typeof ResellerLogsRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/reseller/licenses': {
      id: '/reseller/licenses'
      path: '/licenses'
      fullPath: '/reseller/licenses'
      preLoaderRoute: typeof ResellerLicensesRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/reseller/bypass': {
      id: '/reseller/bypass'
      path: '/bypass'
      fullPath: '/reseller/bypass'
      preLoaderRoute: typeof ResellerBypassRouteImport
      parentRoute: typeof ResellerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store-pages': {
      id: '/admin/store-pages'
      path: '/store-pages'
      fullPath: '/admin/store-pages'
      preLoaderRoute: typeof AdminStorePagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bypass': {
      id: '/admin/bypass'
      path: '/bypass'
      fullPath: '/admin/bypass'
      preLoaderRoute: typeof AdminBypassRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reviews': {
      id: '/_public/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof PublicReviewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/marketplace': {
      id: '/_public/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof PublicMarketplaceRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicMarketplaceRoute: typeof PublicMarketplaceRoute
  PublicReviewsRoute: typeof PublicReviewsRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicMarketplaceRoute: PublicMarketplaceRoute,
  PublicReviewsRoute: PublicReviewsRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBypassRoute: typeof AdminBypassRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminResellersRoute: typeof AdminResellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorePagesRoute: typeof AdminStorePagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBypassRoute: AdminBypassRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminResellersRoute: AdminResellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorePagesRoute: AdminStorePagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResellerRouteChildren {
  ResellerBypassRoute: typeof ResellerBypassRoute
  ResellerLicensesRoute: typeof ResellerLicensesRoute
  ResellerLogsRoute: typeof ResellerLogsRoute
  ResellerUsersRoute: typeof ResellerUsersRoute
  ResellerIndexRoute: typeof ResellerIndexRoute
}

const ResellerRouteChildren: ResellerRouteChildren = {
  ResellerBypassRoute: ResellerBypassRoute,
  ResellerLicensesRoute: ResellerLicensesRoute,
  ResellerLogsRoute: ResellerLogsRoute,
  ResellerUsersRoute: ResellerUsersRoute,
  ResellerIndexRoute: ResellerIndexRoute,
}

const ResellerRouteWithChildren = ResellerRoute._addFileChildren(
  ResellerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResellerRoute: ResellerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
